services:
  mongo:
    image: mongo:7
    container_name: meeting-summary-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - meeting-summary-internal
      - infra
    ports:
      - "27017:27017"

  backend:
    image: ghcr.io/wisdom-youth-mlpe/meeting-summary-backend:latest
    container_name: meeting-summary-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/meeting_app
      - CORS_ORIGIN=https://meeting.wisdommlpe.site
    depends_on:
      - mongo
    networks:
      - meeting-summary-internal
      - infra
    ports:
      - "3001:3001"

  frontend:
    image: ghcr.io/wisdom-youth-mlpe/meeting-summary-frontend:latest
    container_name: meeting-summary-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - meeting-summary-internal
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=https://meeting.wisdommlpe.site
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sample-app.rule=Host(`meeting.wisdommlpe.site`)"
      - "traefik.http.routers.sample-app.entrypoints=websecure"
      - "traefik.http.routers.sample-app.tls=true"
      - "traefik.http.routers.sample-app.tls.certresolver=myresolver"
      - "traefik.http.services.sample-app.loadbalancer.server.port=80"
      # HTTP to HTTPS redirect
      - "traefik.http.routers.sample-app-http.rule=Host(`meeting.wisdommlpe.site`)"
      - "traefik.http.routers.sample-app-http.entrypoints=web"
      - "traefik.http.routers.sample-app-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

networks:
  meeting-summary-internal:
    external: true
  infra:
    external: true

volumes:
  mongo-data:
