services:
  mongo:
    image: mongo:7
    container_name: meeting-summary-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - meeting-summary-internal
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    container_name: meeting-summary-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/meeting_app
      - CORS_ORIGIN=http://localhost:5174
    depends_on:
      - mongo
    networks:
      - meeting-summary-internal
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    container_name: meeting-summary-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - meeting-summary-internal
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001

networks:
  meeting-summary-internal:


volumes:
  mongo-data:
