services:
  - type: web
    name: meeting-summary-backend
    env: node
    plan: free
    repo: https://github.com/fahizkp/meeting-summary-app
    branch: master
    rootDir : backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    runtime: static
    name: meeting-summary-frontend
    env: static
    plan: free
    repo: https://github.com/fahizkp/meeting-summary-app
    branch: master
    rootDir : frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://meeting-summary-app-m36y.onrender.com
      - key: VITE_API_URL
        value: https://meeting-summary-app-m36y.onrender.com

